### ISSUE TITLE
Hello can i ask something?

### ISSUE THREAD

**Issue by MikuRevenge** [EvolSoft/EmailConfirm#2]
Hello sorry if im in wrong section ..im a noobs 

How can i install this? Thx !

**Comment by Flavius12** [comment]
This plugin is still not finished. I'll work on it when I have a bit of free time

**Comment by MikuRevenge** [comment]
How can i put The serverauth on my database? full instructions pls? im noobs :p

**Comment by Flavius12** [comment]
You must enable mysql from ServerAuth plugin config.yml file. Then fill mysql related fields with your MySQL database details
